name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  swift:
    name: build and run tests
    runs-on: macos-12

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: set up Xcode 14 beta
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.0-beta'
    - name: set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.GHA_PRIVATE_SSHKEY }}
    - name: build, tests
      run: xcodebuild -scheme "WooshyWindowToTheForeground" -configuration "Debug" -usePackageSupportBuiltinSCM -derivedDataPath $GITHUB_WORKSPACE -enableCodeCoverage YES clean build test
