name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  swift:
    name: on Monterey
    runs-on: macos-12

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: checkout AlfredWorkflowScriptFilter
      uses: actions/checkout@v3
      with:
        repository: godbout/AlfredWorkflowScriptFilter
        path: AlfredWorkflowScriptFilter
    - name: set up Xcode 14 beta
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.0-beta'
    - name: build, and run tests
      run: xcodebuild -scheme "WooshyWindowToTheForeground" -configuration "Debug" -usePackageSupportBuiltinSCM -derivedDataPath $GITHUB_WORKSPACE -enableCodeCoverage YES clean build test
