name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  swift:
    name: on Big Sur
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: build, and run tests
      run: xcodebuild -scheme "WooshyWindowToTheForeground" -configuration "Debug" -usePackageSupportBuiltinSCM -derivedDataPath $GITHUB_WORKSPACE -enableCodeCoverage YES clean build test
